os: linux
language: node_js
node_js:
  - stable
  - lts/*
install:
  - npm install
cache:
  directories:
    - node_modules
notifications:
  email: false    
jobs:
  include:
    - stage: release
      before_script:
        - npm prune
      script:
        - npm run test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - npm run semantic-release
